export const ADD_CART = 'ADD_CART'              // 添加购物车
export const REMOVE_CART = 'REMOVE_CART'        // 删除购物车
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'// 改变商品数量
export const CHOICE_CHECKED = 'CHOICE_CHECKED'  // 是否选中
export const ISCHECK_ALL = 'ISCHECK_ALL'        // 是否全选
export const GET_GART_LISTS = 'GET_GART_LISTS'  // 获取所有商品
export const TIP_NUM = 'TIP_NUM'                // 获取商品中数量
export const USER_INFO = 'USER_INFO'            // 用户名
export const GET_ADDADDRES_INDEX = 'GET_ADDADDRES_INDEX'            // 获取省
export const GET_ADDADDRES_CHILDREN = 'GET_ADDADDRES_CHILDREN'      // 获取市
export const GET_ADDADDRES_DSTRICT = 'GET_ADDADDRES_DSTRICT'        // 获取区